language: node_js
node_js:
  - "stable"

branches:
  only:
  - master

cache:
  directories:
    - node_modules

before_install:
  - npm install -g firebase-tools
  - npm ci

script:
  - npm run lint
  - npm test
  - npm run build

after_success: 
  - sudo chmod -R 777 ./build
  - firebase use default --token $FIREBASE_DEPLOY_TOKEN
  - firebase deploy --token $FIREBASE_DEPLOY_TOKEN